language: java

jdk:
 - oraclejdk8

install:
 - mvn install -Dmaven.test.skip=true

after_success:
  - mvn -pl '!spring-cloud-zuul-ratelimit-dependencies' clean jacoco:prepare-agent verify jacoco:report coveralls:report sonar:sonar

notifications:
  email:
   - marcos.hgb@gmail.com