zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/
    serviceB:
      path: /serviceB
      url: forward:/
    serviceC:
      path: /serviceC
      url: forward:/
    serviceD:
      strip-prefix: false
      path: /serviceD/**
      url: forward:/
    serviceE:
      path: /serviceE
      url: forward:/
    serviceF:
      strip-prefix: false
      path: /serviceF/**
      url: forward:/
  ratelimit:
    enabled: true
    repository: BUCKET4J_JCACHE
    policy-list:
      serviceA:
        - limit: 10
          refresh-interval: 60
          type:
            - origin
      serviceB:
        - limit: 2
          refresh-interval: 2
          type:
            - origin
      serviceD:
        - limit: 2
          refresh-interval: 60
          type:
            - url
      serviceE:
        - quota: 1
          refresh-interval: 60
          type:
            - origin
      serviceF:
        - limit: 2
          refresh-interval: 60
          type:
            - url_pattern=/serviceF/*/specific
  strip-prefix: true

logging:
  level:
    ROOT: error