name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your question, we will get back to you asap!'' first issue'
        pr-message: 'Thanks for your contribution! Please make sure to link the issue that you are trying to solve and also add tests cases to cover the new code. Thanks!'' first pr'
