name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }} ,thank you for submitting an issue!'
        pr-message: 'Hello @${{ github.actor }}, thanks for your contribution! Please make sure to link the issue that you are trying to solve and also add tests cases to cover the new code. Thanks!'
