name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Marked as stale due inactivity'
        stale-pr-message: 'Marked as stale due inactivity'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
